[package]
name = "solflip"
version = "0.1.0"
description = "SolFlip — provably-fair coin-flip casino on Solana (ORAO VRF)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solflip"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "orao-solana-vrf/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
orao-solana-vrf = { version = "0.6.1", default-features = false, features = ["cpi"] }
